### ISSUE TITLE
Out of range exception in  strcpy_VBsafe(out string sout, string sin)

### ISSUE THREAD

**Issue by sebsebien** [ygrenier/SwissEphNet#17]
Length of the input string must be tested in  strcpy_VBsafe(out string sout, string sin). Here's an example of fix that works well for me:

void strcpy_VBsafe(out string sout, string sin) {          
            while (i < sin.Length && i < 30 && (Char.IsLetterOrDigit(sin[i]) || sin[i] == ' ' || sin[i] == '-'))
                i++;
            sout = sin.Substring(0, i);
        }

**Comment by ygrenier** [comment]
Fixed in PR #19
