### ISSUE TITLE
Asteroid calculation does not work

### ISSUE THREAD

**Issue by sebsebien** [ygrenier/SwissEphNet#18]
The calculation of the 6 main asteroïds (Chiron, Pallas, ...) is working fine. However, the calculation of most other asteroïds does not work. 

You can reproduce the error by calling for example swe_calc_ut() or swe_pheno_ut().

As planet number, you can use use 10005 (the file se00005.se1 or se00005s.se1 must be present in your ephemeris folder). It will crash while reading the file ('le format de la chaîne d'entrée est incorrect').

I get the same issue for most asteroids. For asteroid 'Amor' (number 11221, file se01221s.se1), however, it works fine.

**Comment by ygrenier** [comment]
Fixed on PR #20
