### ISSUE TITLE
Catching of errors 

### ISSUE THREAD

**Issue by sebsebien** [ygrenier/SwissEphNet#21]
This is not really a bug but a suggestion for improvement. As you don't systematically use 'try-catch' blocks, it's very difficult to debug your library. If you can implement my suggestion (in your generation script), I will be able to test the full library and provide you with clear indications about the origin of the remaining issues that I have encountered.

Suggestion:
Would it be possible to include in your generation script, the automatic creation of a try catch block for each method? In the 'try' block, you just put the actual code of the method. In the 'catch' block, you just throw a new exception, concatenated with the name of the method (in which the catch block is present) and with the exception message itself. By doing so, you can trace back all the issues up to the source of the exception (I am using this mechanism in all my software and it's very efficient for debugging).

Example for one method (to be done for all methods):

Instead of generating:
public Int32 swe_lmt_to_lat(double tjd_lmt, double geolon, out double tjd_lat, ref string serr)
        {
            Int32 retval; serr = null;
            double E, tjd_lmt0;
            tjd_lmt0 = tjd_lmt - geolon / 360.0;
            retval = swe_time_equ(tjd_lmt0, out E, ref serr);
            tjd_lat = tjd_lmt + E;
            return retval;
        }

You generate:
public Int32 swe_lmt_to_lat(double tjd_lmt, double geolon, out double tjd_lat, ref string serr)
 {
             try
            {
                Int32 retval; serr = null;
                double E, tjd_lmt0;
                tjd_lmt0 = tjd_lmt - geolon / 360.0;
                retval = swe_time_equ(tjd_lmt0, out E, ref serr);
                tjd_lat = tjd_lmt + E;
                return retval;
            }
            catch (Exception exc)
            {
                throw new Exception("swe_lmt_to_lat() " + exc.Message);
            }
}

Many thanks in advance for your answer,

sebsebien

**Comment by ygrenier** [comment]
I don't understand your problem. When an exception is raised, there is the stack trace of the calls in the Exception.StackTrace property, Is not enough ?

Else, I don't generating the code! I rewrite all from the C code by hand.

Regards,
Yanos

**Comment by sebsebien** [comment]
Yes, it's enough. You can close the issue.

Best Regards,
