### ISSUE TITLE
Dll vs port

### ISSUE THREAD

**Issue by afucher** [ygrenier/SwissEphNet#25]
It's possible to use the dll using DllImport in C#? If the answer is yes, why use a port and not the dll?

**Comment by ygrenier** [comment]
Yes you can use the dll in C#, like this project https://github.com/vishnukool/swissEphemeris testing some Swiss Ephemeris imported functions.

Why use the port ? The main reason is when you can't use the DLL (like in Xamarin project, or UWP application). 

I created the project for a friend who needed to use Swiss Ephemeris on the old "Metro" application on Windows 8.

**Comment by afucher** [comment]
Thks for your explanation!
But using a port, is more complicated to mantain the code updated, right? I need to make a diff in the main lib (swisseph C) and than replicate in the port, every time that the main lib has an update.

**Comment by ygrenier** [comment]
Yes it's a little complicated to update the code, we need to compare the files, and update de C code to C#, it's take some times. It's for that there is a laps time before the SwissEphNet library was updated from the official C Library.

But if you're not hurry, generally the Nuget package is updated in one or two week after a new release generally. So far no one has complained ;)

**Comment by afucher** [comment]
Just thinking when someday you don't want to make more this update, I don't know if I know how to do it by myself.... 

Thks for your answers :)

**Comment by ygrenier** [comment]
You're welcome if you want to help.

Fortunately the updates are not very frequent, so it's not a very restrictive job.
