### ISSUE TITLE
Getting Declinations

### ISSUE THREAD

**Issue by sbalinder** [ygrenier/SwissEphNet#26]
Hello,

Which method should be used to get "Declinations" along with Longitude and Speed?

Please advise. 

Thanks for your help.

**Comment by sbalinder** [comment]
Kindly advise how to get "Declinations" for Cusps?

**Comment by ygrenier** [comment]
Sorry for the delay.

I don't use the Library, I make it for a friend. So I can't help you for the calculations.

You can ask the question in the official SwissEphemeris Library group http://groups.yahoo.com/group/swisseph/ where there are the people are better about the ephemeris calculation. After you can apply the response to the SwissEphNet.
