### ISSUE TITLE
SWE_SET_EPHE_PATH Can't find ephemeris files 

### ISSUE THREAD

**Issue by Ekhazeni** [ygrenier/SwissEphNet#40]
Greetings, 
I tried many types of making path either dynamic or static like C:\\Ephe, C:\Ephe\, C://Ephe etc but none of them are working. I use VB.Net 
Am I doing something wrong or it's an issue? 
Thank you  

![image](https://user-images.githubusercontent.com/21014708/60361231-ec790400-99f2-11e9-9870-f5a524926bc6.png)

**Comment by ygrenier** [comment]
Hi,

Did you handle the OnLoadFile event like describe on this page: [Loading files](https://github.com/ygrenier/SwissEphNet/wiki/Loading-files) ?

It's in C# but I think you in VB.Net it's like:
```vb
        Using sweph = New SwissEphNet.SwissEph()
            sweph.OnLoadFile += Function(s, e)
                                  ' Loading file
                                End Function
        End Using
```

Regards

**Comment by Ekhazeni** [comment]
Hi,
It worked! Thank you. 

The code for VB.Net is

`       AddHandler sweph.OnLoadFile, Sub(s, Args)
                                             Dim ephepath = Mypath+";.;C:\\ephe;"
                                           '  Loadfiles (s, Args)  
                                         End Sub

**Comment by ygrenier** [comment]
Good news.

**Comment by Senapathiy** [comment]
> Hi, It worked! Thank you.
> 
> The code for VB.Net is
> 
> ` AddHandler sweph.OnLoadFile, Sub(s, Args) Dim ephepath = Mypath+";.;C:\ephe;" ' Loadfiles (s, Args) End Sub

I'm new to vb.net it's showing friend read only property error 

If it possible kindly give full code like you shared previous image 

Thnaks
