### ISSUE TITLE
Fixed Stars

### ISSUE THREAD

**Issue by Ekhazeni** [ygrenier/SwissEphNet#41]
Hi Yan, 
I faced some issues using fixed stars functions. I also downloaded the latest "sefstars.txt" but the result is the same. 

1- The two new fixed star functions (**swe_fixstar2_ut** and **swe_fixstar2**)  are not working at at all. 
2- The old functions (**swe_fixstar_ut** and **swe_fixstar**) are not working properly. 
in 

```
Star=1          'Integer works However a string should be returned by Ref and Star is an integer so it fails
Star=10        

Star="1"        'Works up to 9 
Star="10"      'Doesn't Work
Star="Spica" 'Direct name works!
Star="alVir"  'Doesn't work!
Star=",alVir" 'Doesn't work! 

SWE_Chart.swe_fixstar(STAR, tjd_ut, fxflag, stararray, serr)   

```

As the original C++ code based on char*, using Sweph32.dll I was using type StringBuilder and it was working fine. Please take a look.

All the best,
Ehsan

**Comment by ygrenier** [comment]
Hi,

Thanks for the report. I'll look it asap.

**Comment by Ekhazeni** [comment]
Hi there,

Any progress? 

Thank you :-)

**Comment by ygrenier** [comment]
Hi,

Sorry I'm working slowly because lot of jobs and familly constraints :)

I found small issues of the portage about the fixed star file parsing. I also detect more complex issues about the sort and the search of the fixed star.

I'm working to fix it asap.

Regards

**Comment by ygrenier** [comment]
Fixed : https://github.com/ygrenier/SwissEphNet/releases/tag/v2.8.0.2 

The package is updated to Nuget gallery.

I created a test class Issue41Test for this work, normally I check all kind of search, but if you can verify this can help me :)

Thanks, regards

Yanos
